include:
  - docker-compose.yml

services:
  app:
    container_name: card-game-main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:3000'
    environment:
      MONGO_URL: "mongodb"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
