version: '3'
services:
  redis:
   image: "redis:alpine"
   ports:
     - 6379:6379

  mongodb:
    image: "mongo"
    ports:
      - 27017:27017

  rabbitMQ:
    image: "rabbitmq:alpine"
    ports:
      - 5672:5672
      - 15672:15672

